import { MemoryTile } from "memorytile.slint";

struct TileData {
  image: image,
  image-visible: bool,
  solved: bool,
}

export component AppWindow inherits Window {
  title: "Memory";
  min-width: 326px;
  min-height: 326px;
  background: #550055;

  callback check-if-pair-solved();
  in property <bool> disable-tiles;

  in property <[TileData]> memory-tiles: [
    { image: @image-url("icons/at.png") },
    { image: @image-url("icons/balance-scale.png") },
    { image: @image-url("icons/bicycle.png") },
    { image: @image-url("icons/bus.png") },
    { image: @image-url("icons/cloud.png") },
    { image: @image-url("icons/cogs.png") },
    { image: @image-url("icons/motorcycle.png") },
    { image: @image-url("icons/video.png") },
  ];

  for tile[i] in memory-tiles : MemoryTile {
    x: mod(i, 4) * 74px + 18px;
    y: floor(i / 4) * 74px + 18px;
    width: 64px;
    height: 64px;
    icon: tile.image;
    open-curtain: tile.image-visible || tile.solved;
    // propagate the solved status from the model to the tile
    solved: tile.solved;
    clicked => {
      if (!root.disable-tiles) {
        tile.image-visible = !tile.image-visible;
        root.check-if-pair-solved();
      }
    }
  }
}
